default:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10240
    epsilon: 0.2
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    learning_rate_schedule: linear
    max_steps: 5.0e4
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 1000
    use_recurrent: false
    vis_encode_type: simple
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
            
TankShoot:
    summary_freq: 5000
    time_horizon: 128
    batch_size: 128
    buffer_size: 2048
    beta: 1.0e-2
    max_steps: 1.0e6
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
        curiosity:
            strength: 0.02
            gamma: 0.99
            encoding_size: 256

Driving:
    batch_size: 2048
    normalize: true
    beta: 1e-4
    num_layers: 2
    hidden_units: 256
    init_entcoef: 
    beta: 5.0e-3
    buffer_size: 12288
    max_steps: 1.0e7
    summary_freq: 2000
    lambd: 0.925
    num_epoch: 5
    time_horizon: 150
    epsilon: 0.3
    use_recurrent: true
    sequence_length: 50
    memory_size: 128
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.8
        curiosity:
            strength: 0.1
            gamma: 0.95
            encoding_size: 128